fix import error
Fixes ImportError: cannot import name 'buildpomupdate'
from partially initialized module 'update' (most
likely due to a circular import)